from __future__ import annotations

from datetime import UTC, datetime

from event_radar.models import AccountConfig, SourcePlatform


def seed_accounts() -> list[AccountConfig]:
    now = datetime.now(UTC)
    return [
        AccountConfig(
            id="seed_x_real_donald_trump",
            source=SourcePlatform.X,
            entity_key="donald_trump",
            display_name="Donald Trump",
            handle="realDonaldTrump",
            source_url="https://x.com/realDonaldTrump",
            official=True,
            active=True,
            authority_rank=100,
            metadata={"role": "principal"},
            created_at=now,
            updated_at=now,
        ),
        AccountConfig(
            id="seed_truth_real_donald_trump",
            source=SourcePlatform.TRUTH_SOCIAL,
            entity_key="donald_trump",
            display_name="Donald Trump",
            handle="realDonaldTrump",
            source_url="https://truthsocial.com/@realDonaldTrump",
            official=True,
            active=True,
            authority_rank=100,
            metadata={"role": "principal"},
            created_at=now,
            updated_at=now,
        ),
        AccountConfig(
            id="seed_x_netanyahu",
            source=SourcePlatform.X,
            entity_key="benjamin_netanyahu",
            display_name="Benjamin Netanyahu",
            handle="netanyahu",
            source_url="https://x.com/netanyahu",
            official=True,
            active=True,
            authority_rank=96,
            metadata={"role": "principal"},
            created_at=now,
            updated_at=now,
        ),
        AccountConfig(
            id="seed_x_israeli_pm",
            source=SourcePlatform.X,
            entity_key="benjamin_netanyahu",
            display_name="Israeli Prime Minister",
            handle="IsraeliPM",
            source_url="https://x.com/IsraeliPM",
            official=True,
            active=True,
            authority_rank=93,
            metadata={"role": "office"},
            created_at=now,
            updated_at=now,
        ),
        AccountConfig(
            id="seed_x_irimfa_en",
            source=SourcePlatform.X,
            entity_key="iran_foreign_ministry",
            display_name="Iran Foreign Ministry",
            handle="IRIMFA_EN",
            source_url="https://x.com/IRIMFA_EN",
            official=True,
            active=True,
            authority_rank=88,
            metadata={"role": "foreign_ministry"},
            created_at=now,
            updated_at=now,
        ),
        AccountConfig(
            id="seed_x_iran_un",
            source=SourcePlatform.X,
            entity_key="iran_un_mission",
            display_name="Iran at the UN",
            handle="Iran_UN",
            source_url="https://x.com/Iran_UN",
            official=True,
            active=True,
            authority_rank=86,
            metadata={"role": "un_mission"},
            created_at=now,
            updated_at=now,
        ),
        AccountConfig(
            id="seed_x_irna_english",
            source=SourcePlatform.X,
            entity_key="irna_english",
            display_name="IRNA English",
            handle="IrnaEnglish",
            source_url="https://x.com/IrnaEnglish",
            official=True,
            active=True,
            authority_rank=76,
            metadata={"role": "state_media"},
            created_at=now,
            updated_at=now,
        ),
        AccountConfig(
            id="seed_x_press_tv",
            source=SourcePlatform.X,
            entity_key="press_tv",
            display_name="Press TV",
            handle="PressTV",
            source_url="https://x.com/PressTV",
            official=True,
            active=True,
            authority_rank=74,
            metadata={"role": "state_media"},
            created_at=now,
            updated_at=now,
        ),
    ]
